name: park254_s_parking_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  pin_code_fields: ^7.4.0
  google_maps_flutter: ^2.0.0
  geolocator: ^7.0.0
  dio: ^4.0.0
  flutter_polyline_points: ^0.2.4
  flutter_svg: ^0.19.1
  geocoding: ^2.0.0
  http: ^0.13.4
  uuid: ^2.2.2
  percent_indicator: '^2.1.7+2'
  clippy_flutter: ^1.1.1
  custom_info_window: ^1.0.0
  camera: ^0.5.2+1
  path_provider: ^2.0.0
  path: ^1.7.0
  flutter_secure_storage: ^3.3.5
  shared_preferences: ^2.0.0
  encrypt: ^4.1.0
  image_cropper: ^3.0.0
  image_picker: ^0.7.0
  cloudinary_public: ^0.8.0
  overlay_support: ^1.0.5
  provider: ^4.3.3
  firebase_core: ^1.0.0
  firebase_auth: ^1.0.0
  barcode_scan2: ^4.2.1
  qr_flutter: ^3.2.0
  mpesa: ^2.0.0
  mpesa_flutter_plugin: ^1.0.0
  google_sign_in: ^4.5.9
  jwt_decode: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/Park254_logo.png
    - assets/images/Park254_logo.svg
    - assets/images/parking-icon.png
    - assets/images/parking_photos/parking_1.jpg
    - assets/images/parking_photos/parking_2.jpg
    - assets/images/parking_photos/parking_3.jpg
    - assets/images/parking_photos/parking_4.jpg
    - assets/images/parking_photos/parking_5.jpg
    - assets/images/parking_photos/parking_6.jpg
    - assets/images/parking_photos/placeholder_1.png
    - assets/images/parking_photos/placeholder_2.png
    - assets/images/parking_photos/placeholder_3.png
    - assets/images/parking_photos/placeholder_4.jfif
    - assets/images/profile/profile-1.jpg
    - assets/images/profile/profile-2.jpg
    - assets/images/profile/kenya-flag-icon.png
    - assets/images/profile/visa.svg
    - assets/images/profile/visa_2.svg
    - assets/images/profile/mpesa.svg
    - assets/images/Onboarding/running.svg
    - assets/images/Logo/PARK_254_600x600.jpg
    - assets/images/Logo/PARK_254_1000x400.jpg
    - assets/images/Logo/PARK_254_1000x400_blk.jpg
    - assets/images/Logo/PARK_254_1000x400_wht.png
    - assets/images/Logo/PARK_254_1000x400_wht-01.svg
    - assets/images/Logo/PARK_254_1000x400-01.svg
    - assets/images/pin_icons/
    - assets/images/pin_icons/parking-icon-1.svg
    - assets/images/pin_icons/parking-icon-2.svg
    - assets/images/pin_icons/parking-icon-3.svg
    - assets/images/pin_icons/location-pin.svg
    - assets/images/qrcode.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
